# Generated by Django 4.2.3 on 2023-08-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlisT',
        ),
    ]
