# Generated by Django 4.2.3 on 2023-08-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product_qty',
            field=models.IntegerField(default=None),
        ),
    ]
