# Generated by Django 4.2.1 on 2023-08-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_color_is_available_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
