# Generated by Django 4.2.1 on 2023-08-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantimage',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
