# Generated by Django 4.2.1 on 2023-08-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variant', '0002_variantimage_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
