# Generated by Django 4.2.1 on 2023-08-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
